apiVersion: apps/v1 #this is like a bucket of kubernetes , deployment is is apps/v1 and pods is in v1
kind: Deployment
metadata:
  name: orders-depl # name of deployment
spec:
  replicas: 1 #number of pods to run
  selector: # which pod to run , so matchLabel -> find everything with label "auth"(just a key value pair...app is not important ..you can name anything)
    matchLabels:
      app: orders
  template: # pod config file
    metadata:
      labels:
        app: orders # the tabel which we apply above
    spec:
      containers:
        - name: orders
          image: us.gcr.io/ticketing-dev-380007/orders
          imagePullPolicy: Always
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            
---
apiVersion: v1
kind: Service
metadata:
  name: orders-srv
spec:
  selector:
    app: orders
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000
